#pragma once

enum tnumber { TEOF, TERROR, TBEGIN, TEND, TIDEN, TASSIGN, TADD, TNUM, TSEMI, TCONST, TELSE, TIF, TINT, TRETURN, TVOID, TWHILE, TEQUAL, TNOTEQU, TLESSE, TGREATE, TAND, TOR, TINC, TDEC, TADDASSIGN, TSUBASSIGN, TMULASSIGN, TDIVASSIGN, TMODASSIGN, TIDENT, TNUMBER };