#pragma once

enum tnumber { TEOF, TERROR, TBEGIN, TEND, TSMALLBL, TSMALLBR, TBIGBL, TBIGBR, TIDEN, TASSIGN, TPLUS, TMINUS, TSTAR, TSLASH, TDOT, TNUM, TMOD, TCONST, TELSE, TIF, TINT, TRETURN, TVOID, TWHILE, TEQUAL, TNOTEQU, TLESS, TGREAT, TLESSE, TGREATE, TNOT, TAND, TOR, TINC, TDEC, TBQUOTE, TSQUOTE, TADDASSIGN, TSUBASSIGN, TMULASSIGN, TDIVASSIGN, TMODASSIGN, TIDENTIFIER, TNUMBER, TCOMMENT, TCOMMENTS, TSEPARATOR, TSEMI, TCOMMA };
enum errorTypes { noerror, illid_digit, illid_long, illsp, overfl };
